name: MergeDevelopToDevelop

on:
  workflow_dispatch:
    inputs:
        from:
            description: 'From branch'
            required: true
        to:
            description: 'To branch'
            required: true

jobs:
    create_pull_request:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: 2.7
            - name: Install Bundler
              run: |
                gem install bundler
                bundle install
            - name: Get Build Number
              id: build_number
              run: |
                BUILD_NUMBER=$(cd .. && xcodebuild -showBuildSettings | grep CURRENT_PROJECT_VERSION | tr -d 'CURRENT_PROJECT_VERSION =' | xargs)
                echo "Build Number: $BUILD_NUMBER"
                echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
            - name: switch to from branch and rename
              run: |
                git checkout ${{ github.event.inputs.from }}
                git branch -m merge-${{ github.event.inputs.from }}${{ env.BUILD_NUMBER }}-to-${{ github.event.inputs.to }}
                git push origin merge-${{ github.event.inputs.from }}${{ env.BUILD_NUMBER }}-to-${{ github.event.inputs.to }}
