name: MergeDevelopToDevelop

on:
  workflow_dispatch:
    inputs:
        from:
            description: 'From branch'
            required: true
        to:
            description: 'To branch'
            required: true

jobs:
    create_pull_request:
        runs-on: macos-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
            - run: |
                git config --local user.name "${GitHub_ACTOR}"
                git config --local user.email "${GitHub_ACTOR}@users.noreply.github.com"
            - name: switch to from branch and rename
              run: |
                git checkout -b merge-${{ github.event.inputs.from }}-to-${{ github.event.inputs.to }}
                git push origin merge-${{ github.event.inputs.from }}-to-${{ github.event.inputs.to }}
            - name: Create Pull Request
              uses: actions/github-script@v6
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                  github.rest.pulls.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: 'Merge ${{ github.event.inputs.from }} to ${{ github.event.inputs.to }}',
                    body: '${{ github.event.inputs.from }}から${{ github.event.inputs.to }}へマージするPRを作成します。',
                    head: 'merge-${{ github.event.inputs.from }}-to-${{ github.event.inputs.to }}',
                    base: '${{ github.event.inputs.to }}'
                  })
