name: MergeDevelopToDevelop

on:
  workflow_dispatch:
    inputs:
        from:
            description: 'From branch'
            required: true
        to:
            description: 'To branch'
            required: true

jobs:
    create_pull_request:
        runs-on: macos-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: switch to from branch and rename
              run: |
                git checkout -b merge-${{ github.event.inputs.from }}-to-${{ github.event.inputs.to }}
                git push origin merge-${{ github.event.inputs.from }}-to-${{ github.event.inputs.to }}
            - name: Create Pull Request
              run: |
                gh pr create \
                --base ${{ github.event.inputs.to }} \
                --head ${{ github.event.inputs.from }} \
                --title "merge develop to develop" \
                --body "This is an auto generated PR."
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
