name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.0'

      - name: UnitTests
        run: xcodebuild test -project tca-sample.xcodeproj -scheme tca-sampleTests -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 14 Pro,OS=16.4'
