name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'

#      - name: UnitTests
#        run: xcodebuild test -project tca-sample.xcodeproj -scheme tca-sampleTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=Any iOS Simulator Device'

      - name: Setup ios-sim
        run: brew install ios-sim

      - name: Add iOS Simulator
        run: ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-13, 15.0"

      - name: UnitTests
        run: xcodebuild test -project tca-sample.xcodeproj -scheme tca-sampleTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13'

